name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    name: Validate by building and testing
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: Set up node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run tests
        run: yarn test --passWithNoTests

      - name: Build
        run: yarn run build

  validate-docker-build:
    name: Validate docker image build
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/docker-build-push.yml@main
    with:
      docker-image: ghcr.io/vycius/example
      environment: test
      runs-on: ubuntu-latest
      latest-tag: true
      push: false
