name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Choose deploy environment

jobs:
  deploy-by-trigger:
    name: Release to production
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Deploy Workflow
        run: |
          gh workflow run test.yml --repo vycius/private-repo-sandbox --field environment=dev
          
          # Retrieve the databaseId using the GitHub CLI
          databaseId=$(gh run list --repo vycius/private-repo-sandbox --workflow=test.yml --json=databaseId --limit=1 --jq='.[0].databaseId')
          
          # Watch the workflow run using the GitHub CLI
          gh run watch --repo vycius/private-repo-sandbox "$databaseId"
        shell: bash
