name: Deploy v2

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Choose deploy environment

jobs:
  deploy-by-trigger-v2:
    name: Release to production
    runs-on: ubuntu-latest
    environment: Production
    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2

      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: vycius
          repo: ${{ secrets.GH_DEPLOY_REPO }}
          github_token: ${{ secrets.GH_DEPLOY_TOKEN }}
          workflow_file_name: ${{ secrets.GH_DEPLOY_WORKFLOW }}
          client_payload: '{"environment": "dev"}'

  deploy-by-trigger-v3:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - run: echo deploy-by-trigger-v3
      
  deploy-by-trigger-v4:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - run: echo deploy-by-trigger-v4
