name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Choose deploy environment

jobs:
  deploy-by-trigger:
    name: Release to production
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Deploy Workflow
        run: gh workflow run test.yml --repo vycius/private-repo-sandbox --field environment=dev
        shell: bash

      - name: Retrieve databaseId
        id: retrieve-databaseId
        run: |
          echo "databaseId=$(gh run list --repo vycius/private-repo-sandbox --workflow=test.yml --json=databaseId --limit=1 --jq='.[0].databaseId')" >> GITHUB_ENV
        shell: bash

      - name: Watch workflow run
        run: gh run watch --repo vycius/private-repo-sandbox "${{ env.databaseId }}"
        shell: bash