name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Choose deploy environment

jobs:
  deploy-by-trigger:
    name: Release to production
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Trigger Deploy Workflow
        run: |
          gh workflow run ${{ secrets.GH_DEPLOY_WORKFLOW }} --repo ${{ secrets.GH_DEPLOY_REPO }} --field environment=${{ inputs.environment }}

      - run: echo $(gh run list --repo ${{ secrets.GH_DEPLOY_REPO }} --workflow ${{ secrets.GH_DEPLOY_WORKFLOW }} --json databaseId --limit 1 --jq '.[0].id')

      - name: Get runId
        id: get-run-id
        run: |
          runId=$(gh run list --repo ${{ secrets.GH_DEPLOY_REPO }} --workflow ${{ secrets.GH_DEPLOY_WORKFLOW }} --json databaseId --limit 1 --jq '.[0].id')
          echo "::set-output name=runId::runId"

      - run: echo ${{ steps.get-run-id.outputs.runId }}

      - name: Wait for Deploy Workflow to Complete
        run: |
          gh run watch ${{ steps.get-run-id.outputs.runId }} --repo ${{ secrets.GH_DEPLOY_REPO }} --exit-status
